### ISSUE TITLE
Only first thumb is shown

### ISSUE THREAD

**Issue by tin2tin** [shish/blender-ikea-browser#5]
Very cool project. I didn't know that there is an API for IKEA furniture. 

You properly already know, but currently, only the first thumb is loaded:
![image](https://github.com/user-attachments/assets/21be513e-d778-4f44-acc7-fd24b66fa499)

For running it in Blender 4.3 "Allow Online Access" to be checked:
![image](https://github.com/user-attachments/assets/5fcd5f16-b00a-4eae-8d02-fb4185275009)

For ease of use maybe you could add Install/Uninstall Dependencies button in the Add-on preferences(I have buttons like that in a couple of my add-ons)? Or you could point users to use this add-on for installing the dependency module: https://github.com/amb/blender_pip

**Comment by shish** [comment]
> You properly already know, but currently, only the first thumb is loaded

I've seen this, but can't figure out why yet - specifically the first time a set of search results are shown, all of the thumbnails are downloaded into the cache, but only the first is displayed. If you then make the same search again, all the thumbnails appear to be loaded correctly...


> For ease of use maybe you could add Install/Uninstall Dependencies button in the Add-on preferences

With the new Extension system in 4.2, this shouldn't be necessary -- the .zip file distributed via extensions.blender.org should have all the dependencies bundled into it

(If you mean for development, for people who are running the code from github... I don't actually know that workflow myself -- right now, every time I update the code, I am building a whole new .zip file and reinstalling it :sweat_smile: )

**Comment by shish** [comment]
> It currently doesn't automatically install the dep. when installing the add-on

That is weird, it seems to be working for me (as in, I take a vanilla 4.2 install, prefs -> add-ons -> install from .zip -> select ikea_browser.zip -> it all seems to work with no extra steps)


> If you're using an external IDE [...]

That is excellent to know, thank you, that'll speed up my development cycle quite considerably :D
