### ISSUE TITLE
IMPORT ERROR - AttributeError: Calling operator "bpy.ops.import_scene.gltf" error, could not be found

### ISSUE THREAD

**Issue by anonimo-creator** [shish/blender-ikea-browser#8]
I installed the addons, I see the icons correctly but when I try to import the models I get this error:

 Python: Traceback (most recent call last): File "C:\Users\loren\AppData\Roaming\Blender Foundation\Blender\ 4.2\extensions\user_default\ikea_browser\__init__.py", line 83, in execute bpy.ops.import_scene.gltf(filepath=ikea.get_model(self.itemNo)) File "D:\Program Files\Blender Foundation\Blender 4.2 \4.2\scripts\modules\bpy\ops.py", line 109, in __call__ ret = _op_call(self.idname_py(), kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.import_scene.gltf" error, could not be found

First of all that i have already installed python 3.11

how do i solve the problem?
thanks

**Comment by shish** [comment]
This function should come as part of blender by default - have you manually disabled it? My guess is that this would be `Preferences` -> `Add-ons` -> `glTF 2.0 format`

(If that has been disabled, then I wonder if there's a way for one add-on to specify that it needs certain base functionality to be enabled...)

**Comment by shish** [comment]
(I can confirm that when I go and disable the glTF add-on, I start seeing this error when importing the glTF models from ikea :thinking: )
